### ISSUE TITLE
Sublime text shows compound letter as splitted

### ISSUE THREAD

**Issue by bsde1234** [smc/AnjaliOldLipi#1]
When I try to open file containing malayalam words, sublime text shows compound letters as splitted letters. For example the word `ഉത്തരം` shows as `ഉത് തരം` without space in it. PS: I can't write here without space as it will show as normal compound letter.
But in Visual studio code, it works correctly. Can you please tell me where is the problem. Thanks.

**Comment by rajeeshknambiar** [comment]
Problem is very likely with Sublime Text, which I’m fairly sure doesn’t support advanced text shaping. Try with another Malayalam font such as Rachana and if the issue remains, it can be concluded the Sublime Text lacks necessary support. If not, do open an issue at https://gitlab.com/smc/fonts/anjalioldlipi (which is where the development happens, this github page is only a mirror).

**Comment by bsde1234** [comment]
Ok. Can you please tell me, if I open wordpad and set AnjaliOldLipi as font, how to type malayalam *without using any additional input tool*. I mean with normal keyboard what keystroke produce malayalam. I tried some keys, all giving english word, Is it really required to have input tools like inscript, gist, or google input tools, panchari etc to produce malayalam words?

**Comment by rajeeshknambiar** [comment]
This is off-topic. Still,

Assuming you are on Windows (10), make use of the in-built Inscript keyboard (see for e.g.: https://www.anoopcnair.com/windows-10-malayalam-language/) or if you prefer transliteration, try Keyman (https://help.keyman.com/keyboard/malayalam/1.1/malayalam).
